#!/usr/bin/env ruby

# TODO, describe how this is invoked.
#
# In the default implementation, account_alias is ignored.

require 'json'
require 'aws-sdk'

def get_proxy
  e = ENV['https_proxy']
  e = "https://#{e}" if e && !e.empty? && !e.start_with?('http')
  return e
end

spec = JSON.parse($stdin.read)
puts "default push-stacks run with argv = #{spec["args"].inspect}"

config = {}
config[:http_proxy] = get_proxy

spec["stacks"].entries.sort_by(&:first).each do |type, details|
  description = JSON.parse(IO.read details["description"])
  description = description["Stacks"][0]

  # Reduce whitespace
  template = JSON.generate(JSON.parse(IO.read details["template"]))

  stack_name = description["StackName"]
  puts "Pushing stack #{stack_name.inspect}"

  start = Time.now

  method = stack_name_or_id = region = nil
  if description["StackId"]
    method = :update_stack
    stack_name_or_id = description["StackId"]
    region = stack_name_or_id.split(/:/)[3] # arn:aws:cloudformation:region:acount:...
  else
    method = :create_stack
    stack_name_or_id = stack_name["stack_name"]
    region = stack_name["region"]
  end
  puts "using #{method} and #{stack_name_or_id} via region #{region.inspect}"

  cfn_client = Aws::CloudFormation::Client.new(config.merge region: region)

  r = cfn_client.send(
    method,
    stack_name: stack_name_or_id,
    template_body: template,
    parameters: description["Parameters"].map do |param|
      {
        parameter_key: param["ParameterKey"],
        parameter_value: param["ParameterValue"],
      }
    end,
    capabilities: description["Capabilities"],
    notification_arns: description["NotificationARNs"],
    tags: description["Tags"].map do |tag|
      {
        key: tag["Key"],
        value: tag["Value"],
      }
    end,
  )
  puts ""

  begin
    # Supplied by https://github.com/rvedotrc/cloudsaw
    since = (start - 60).utc.strftime('%Y-%m-%dT%H:%M:%SZ')
    pid = Process.spawn("cfn-events", "-w", "--since=#{since}", r.stack_id)
    Process.wait pid
  rescue Errno::ENOENT
    puts "To watch stack events, please install cloudsaw <https://github.com/rvedotrc/cloudsaw>"
  end
end
