#!/usr/bin/env ruby

# TODO, describe how this is invoked.
#
# In the default implementation, account_alias is ignored.

require 'json'
require 'aws-sdk'
require 'cfn-events'

def get_proxy
  e = ENV['https_proxy']
  e = "https://#{e}" if e && !e.empty? && !e.start_with?('http')
  return e
end

def watch_stack_events(stack_id, cfn_client, since)
  config = CfnEvents::Config.new
  config.cfn_client = cfn_client
  config.stack_name_or_id = stack_id
  config.wait = true
  config.since = since

  rc = CfnEvents::Runner.new(config).run
  # FIXME do we care about non-zero return code?
end

spec = JSON.parse($stdin.read)
puts "default push-stacks run with argv = #{spec["args"].inspect}"

config = {}
config[:http_proxy] = get_proxy

spec["stacks"].entries.sort_by(&:first).each do |type, details|
  description = JSON.parse(IO.read details["description"])
  description = description["Stacks"][0]

  # Reduce whitespace
  template = JSON.generate(JSON.parse(IO.read details["template"]))

  stack_name = description["StackName"]
  puts "Pushing stack #{stack_name.inspect}"

  start = Time.now

  method = stack_name_or_id = region = nil
  if description["StackId"]
    method = :update_stack
    stack_name_or_id = description["StackId"]
    region = stack_name_or_id.split(/:/)[3] # arn:aws:cloudformation:region:acount:...
  else
    method = :create_stack
    stack_name_or_id = stack_name["stack_name"]
    region = stack_name["region"]
  end
  puts "using #{method} and #{stack_name_or_id} via region #{region.inspect}"

  cfn_client = Aws::CloudFormation::Client.new(config.merge region: region)

  r = cfn_client.send(
    method,
    stack_name: stack_name_or_id,
    template_body: template,
    parameters: description["Parameters"].map do |param|
      {
        parameter_key: param["ParameterKey"],
        parameter_value: param["ParameterValue"],
      }
    end,
    capabilities: description["Capabilities"],
    notification_arns: description["NotificationARNs"],
    tags: description["Tags"].map do |tag|
      {
        key: tag["Key"],
        value: tag["Value"],
      }
    end,
  )
  puts ""

  watch_stack_events r.stack_id, cfn_client, start - 60

end
